name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true

    steps:
      name: Install neovim
      run:
      apt install neovim

      name: Install the plugin
      run:
      git clone https://github.com/Phandal/sdfcli-nvim
      cp sdfcli-nvim ~/.local/share/nvim/