name: Run Tests
on: [push, pull_request]

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        neovim_branch: ["v0.8.0", "nightly"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim_branch }}

      - name: Install luarocks
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt intsall luarocks

      - name: Install luacheck
        run: |
          sudo luarocks install luacheck

      - name: Install vusted
        run: |
          sudo luarocks --lua-version=5.1 install vusted

      - name: Install stylua
        run: |
          curl -sL https://github.com/JohnnyMorganz/StyLua/releases/download/v0.15.1/stylua-linux-x86_64.zip > ./stylua.zip | unzip ./stylua.zip -d ./utils

      - name: Run Tests
        run:
          make integration
