name: Run Tests
on: [push, pull_request]

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        neovim_branch: ["v0.8.0", "nightly"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim_branch }}

      - name: Setup
        run:
          sudo apt update
          sudo apt upgrade -y
          sudo apt intsall luarocks
          sudo luarocks install luacheck
          sudo luarocks --lua-version=5.1 install vusted
          curl -sL https://github.com/JohnnyMorganz/StyLua/releases/download/v0.15.1/stylua-linux-x86_64.zip | unzip ./stylua-linux-x86_64.zip -d ./stylua

      - name: Run Tests
        run:
          make integration
